### ISSUE TITLE
Boost and handbrake does not disable when disabling bot.

### ISSUE THREAD

**Issue by typoEXE** [MarlBurroW/RLMarlbot#12]
As requested by Marl himself...

Something I did find that bothers me a bit is that when I disable the bot in-game, the boost or handbrake remains on which is annoying when trying to take manual control over the car. Is there a way to fix this?

**Comment by MarlBurroW** [comment]
Should be fixed in v1.3.0, can you confirm ?

**Comment by typoEXE** [comment]
> Should be fixed in v1.3.0, can you confirm ?

I confirm that this is fixed!
