### ISSUE TITLE
Request Feature :

### ISSUE THREAD

**Issue by GambitPlayer** [MarlBurroW/RLMarlbot#24]
Hey it's Clix999, first of all thank you to keep the bot updated and trying to fix issues that's cool !

I would like to ask for a feature to be implement : Choose the Rocket League instance to put the bot in.

Currently I can play with the bot in Duo ranked by starting the bot account, inject in his instance (obvious) and then start my personnal instance.

About the Trio ranked well I can't because when I wanna inject I got this message : (see pics)

![image_2024-04-27_130938177](https://github.com/MarlBurroW/RLMarlbot/assets/167632065/53dfe8d4-f556-4110-9416-b7a2d8503565)

Have a good day !

**Comment by MarlBurroW** [comment]
Hi, I'm note sure how does it works in case of multiple instance.
Currently, the script select the process named "RocketLeague.exe".
Does your second instance has a different name to be able to make the difference between theses two processes ?

**Comment by Barzsx** [comment]
![image](https://github.com/MarlBurroW/RLMarlbot/assets/66015688/3ab3a49b-ffc1-4ab4-9380-9224052962f5)
you can distinguish the processes like this, and just add a manual selection of which process to inject the bot to.

**Comment by Barzsx** [comment]
PID - Process ID

**Comment by GambitPlayer** [comment]
that would be useful

**Comment by Kuenec** [comment]
yes!!! this is what i was going to suggest to along with split screen, as thorami bot is able to load multiple instances and split screen. good feature request man!

**Comment by MarlBurroW** [comment]
Ok gonna add this next update

**Comment by MarlBurroW** [comment]
Please check and test release 1.5.0

**Comment by Barzsx** [comment]
How do we input the cli args?

**Comment by MarlBurroW** [comment]
https://github.com/MarlBurroW/RLMarlbot/assets/3024430/bda4d000-0ccf-4d5c-874d-65be8aaf94c3

**Comment by MarlBurroW** [comment]
Implemented in 1.5.0, closed
