### ISSUE TITLE
Rights to PR for auto enabling BOT

### ISSUE THREAD

**Issue by Lorenzeub** [MarlBurroW/RLMarlbot#25]
i have made the feature for enabling the bot automatically can i have the rights for PR?

**Comment by MarlBurroW** [comment]
Cool, PR are authorized for any github users by default. Are you sure you can't submit it ?

**Comment by Lorenzeub** [comment]
Yes j’al une 403

**Comment by MarlBurroW** [comment]
Have you ever done a PR on any other repo? Because it looks like an authentication problem. Did you fork the repo? If you cloned your fork via SSH, have you added your public key in your github settings to be able to push?

**Comment by Lorenzeub** [comment]
I didn’t fork the repo

**Comment by MarlBurroW** [comment]
To make a PR you have to:

- Fork this repo
- Clone your fork on your PC
- Make some changes
- Commit and push your changes
- Create a new pull request on this repo and select your fork and your commit you want to merge
