### ISSUE TITLE
Can't start Marlbot through cloned file, gives me this error!!

### ISSUE THREAD

**Issue by BetaWing** [MarlBurroW/RLMarlbot#30]
Can't start Marlbot through cloned file, gives me this error!! 
![88dY1X3](https://github.com/MarlBurroW/RLMarlbot/assets/21138758/2b46f162-263d-4f6b-818b-e6ddee0590c3)

**Comment by MarlBurroW** [comment]
Ok I guess it's because I've renamed the folder `rlnexto_python` into `rlmarlbot`

**Comment by Blackdz270** [comment]
And the solution ?

**Comment by MarlBurroW** [comment]
You should try to recreate your virtual env with poetry, and reinstall dependencies
