### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Subarashiili** [MarlBurroW/RLMarlbot#35]
how do i use the auto thing? how do i make it work (the auto toggle)

**Comment by kxqsss** [comment]
go to cmd then type cd (then the path to the folder with the exe in it) so for example: "cd C:\Users\User\OneDrive\Desktop\Marlbot" then type the name of the exe with -a behind it; Like this: "marlbot-1.5.0.exe -a".

**Comment by Subarashiili** [comment]
> go to cmd then type cd (then the path to the folder with the exe in it) so for example: "cd C:\Users\User\OneDrive\Desktop\Marlbot" then type the name of the exe with -a behind it; Like this: "marlbot-1.5.0.exe -a".

ty

**Comment by kxqsss** [comment]
No problem!

**Comment by MarlBurroW** [comment]
Thanks to your help @kxqsss
