### ISSUE TITLE
Custom memory writer fails to load

### ISSUE THREAD

**Issue by zekurom** [MarlBurroW/RLMarlbot#5]
```
RLMarlbot\rlnexto_python\main.py", line 11, in <module>
    from memory_writer import memory_writer
ImportError: DLL load failed while importing memory_writer: The specified module could not be found.
```

**Comment by MarlBurroW** [comment]
Are you up to date ?

**Comment by zekurom** [comment]
Yes, tried multiple times

**Comment by MarlBurroW** [comment]
Have you tried with this release: https://github.com/MarlBurroW/RLMarlbot/releases/tag/v1.1.1

**Comment by zekurom** [comment]
Yes, the executable works just can't run the source code with the way you provided in the README

**Comment by MarlBurroW** [comment]
Have you read the issue #1

**Comment by MarlBurroW** [comment]
?

**Comment by zekurom** [comment]
I got it working, thank you for clarifying in requirements the specific python ver
