### ISSUE TITLE
memory_writer false positive

### ISSUE THREAD

**Issue by mikedrugs** [MarlBurroW/RLMarlbot#6]
The memory_writer.pyd file gets deleted by the windows defender why is that?, does it inject something into the game?

**Comment by MarlBurroW** [comment]
No, the memory_writer just write data (VehicleInput) into the game process. But this DLL/Pyd is not injected into the game process.
It uses the windows API to write into a specific process (RocketLeague.exe). I'm not surprised this kind of DLL may be considered as a virus.
I can publish the code of the memory writer if you guys need it

**Comment by MarlBurroW** [comment]
https://github.com/MarlBurroW/RLMarlbot/tree/master/MemoryWriter
Versionned
