### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Lym0s** [MarlBurroW/RLMarlbot#70]
I cant figure out how to use commands for minimap or anything else. Ive seen a thread here that says to drag the exe into command prompt but im just too stupid. Pls help

**Comment by kxqsss** [comment]
I can't send it here because its too big, but there's a video showing how to do it in the faq channel of the discord.

**Comment by kxqsss** [comment]
Nevermind, I just had to compress it: 

https://github.com/MarlBurroW/RLMarlbot/assets/84988696/21ec37fd-5cd9-4aa4-9a3b-4971e4a931ef

**Comment by kxqsss** [comment]
It should run in the same cmd window. You pressed enter after you typed the arguments you want?

**Comment by Lym0s** [comment]
Ye bro I pressed enter XD it seems like my PC just needed some time to run the exe. I think it's fixed but if not, imma be here again

**Comment by Lym0s** [comment]
Oh damn it shows it every time XD
