### ISSUE TITLE
Auto-Run Feature Upon Entering a Round

### ISSUE THREAD

**Issue by Gamerbros104** [MarlBurroW/RLMarlbot#8]
Hello! I just wanted to express my appreciation for the incredible work you've done on this project. I have a suggestion—could you possibly add an auto-run feature that automatically activates the bot when you enter the round?

**Comment by zekurom** [comment]
I agree, I think it should start enabled but still be toggleable with F1

**Comment by MarlBurroW** [comment]
The problem is that I don't want the bot to automatically reactivate if it disabled the bot in the previous game

**Comment by typoEXE** [comment]
> It sounds like a good feature, the problem is that I don't want the bot to automatically reactivate if it disabled the bot in the previous game.

I agree, please keep the function the way it is for that instance.

Something I did find that bothers me a bit is that when I disable the bot in-game, the boost or handbrake remains on which is annoying when trying to take manual control over the car. Is there a way to fix this?

Thank you and I appreciate your work! I am definitely going to follow this project for as long as it's up!

**Comment by MarlBurroW** [comment]
Already noticed the handbrake bug, can you create a dedicated issue about that ?

**Comment by mikedrugs** [comment]
This feature would be amazing since i tend to go afk sometimes, an option in the config json to enable it would be good :)

**Comment by MarlBurroW** [comment]
Add an option in the config.json sounds OK for me

**Comment by BetaWing** [comment]
bump this is a must have if possible to do

**Comment by MarlBurroW** [comment]
Ok this feature is planned for the next minor update (probably 1.5.0)

**Comment by MarlBurroW** [comment]
Please check and test release 1.5.0

**Comment by Gamerbros104** [comment]
> Please check and test release 1.5.0

W update

**Comment by Gamerbros104** [comment]
> Please check and test release 1.5.0

works like butter now at 2k mmr in casual
![Screenshot 2024-04-29 083037](https://github.com/MarlBurroW/RLMarlbot/assets/167694257/ba872e01-6ff8-4095-bc36-d75b76c57312)
